import "./globals.css";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import NavBar from "@/components/layout/NavBar";
import AppInitializer from "@/components/AppInitializer";
import { ThemeProvider } from "next-themes";
import ScrollToTop from "@/components/common/ScrollToTop";
import Footer from "@/components/layout/Footer";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Pershing Agency",
  description: "Generated by create next app",
  icons: {
    icon: "/images/pgs-agency-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable} suppressHydrationWarning>
      <body>
        <NextTopLoader color="#012847" height={6} showSpinner={false} />
        <main>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <AppInitializer />
            <NavBar />
            {children}
            <Footer />
            <ScrollToTop />
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
